### ISSUE TITLE
[Feature] Features Request from Uni-Dock Repo

### ISSUE THREAD

**Issue by zhengh96** [dptech-corp/Uni-Dock-Dev#10]
I reviewed the issues in the Uni-Dock Repo, and there are a few feature requests that should be satisfied with a small amount of development. If possible, I also suggest releasing them along with Uni-Dock v1.1.

- [ ] save scoring components in result SDF file [#57](https://github.com/dptech-corp/Uni-Dock/issues/57)
- [ ] load an SDF ligand file containing multiple ligands [#53](https://github.com/dptech-corp/Uni-Dock/issues/53) (I have read the previous discussion, but since it's a common case, we can re-think the solution.)
- [ ] Explanation on Bias Docking [#39](https://github.com/dptech-corp/Uni-Dock/issues/39)
- [ ] AD4 scoring function [#27](https://github.com/dptech-corp/Uni-Dock/issues/27)
